version: '3'
services:
    api:
        build: ./api
        ports:
            - "8000:8000"
        depends_on: 
            - postgres
        env_file: 
            - api/envs
        networks: 
            - elasticsearch
            - postgres
    indexer:
        build: ./indexer
        depends_on: 
            - elasticsearch
            - postgres
        env_file: 
            - indexer/envs
        networks: 
            - postgres
            - elasticsearch
    postgres:
        image: "postgres:12.2-alpine"
        ports: 
            - "5432:5432"
        volumes:
            - search-for-flight-pgdata:/var/lib/postgresql/data
        env_file: 
            - postgres/envs
    elasticsearch:
        image: "elasticsearch:7.6.2"
        ports: 
            - "9200:9200" 
            - "9300:9300"
        env_file: 
            - elasticsearch/envs
        networks: 
            - elasticsearch
    kibana:
        image: "kibana:7.6.2"
        ports:
            - "5601:5601"

volumes: 
    search-for-flight-pgdata:
        external: true
networks: 
    elasticsearch:
    postgres: