FROM golang:1.14 as builder
WORKDIR /go/src/app
# fetch deps
COPY go.mod ./
RUN go mod download
# build
COPY . .
RUN make build

FROM scratch
COPY --from=builder /go/src/app/app /usr/local/bin/
EXPOSE 9000
CMD ["app"]